### ISSUE TITLE
Need Help?

### ISSUE THREAD

**Issue by adrienemery** [Davideddu/python-cmdmessenger#1]
Hi there, 

thanks for the library for interfacing to CmdMessenger.  Tried it out and worked easily out of the box.  I was thinking of porting over some of the examples to match up with the examples from the C# library too.  

If you are not already working on this I can get a few ported and open a pull request.

Thanks again!

**Comment by depau** [comment]
No I'm not working on it! Go ahead ;)
Thank you very much!

**Comment by depau** [comment]
Solved with #3.
